### ISSUE TITLE
setuptools_autover stubbornly refuses to respect new tags

### ISSUE THREAD

**Issue by jelmew** [janneronkko/setuptools_autover#1]
Hi,

We are using setuptools_autover to create versioned whls. For some weird reason, setuptools_autover keeps building wheels with and old tag version, even though newer tags are available.  The setup versioning simply has  use_autover=True. Any clue or debugging commando ready to find out why it disrespects all kinds of newer tags? Our problems started when we updated our tags from 1.1.7 to 2.0.0.

Kind regards,
Jelmer

**Comment by janneronkko** [comment]
Hi,

Have you changed to using non-annotated tags instead of annotated tags, i.e. you created 2.0.0 tag with `git tag 2.0.0` instead of `git tag -a 2.0.0`?

What does `git describe` and `git describe --tags` output?

If the one with _--tags_ outputs 2.0.0 and the one without outputs _1.1.7_ then that is the case.

**Comment by janneronkko** [comment]
@jelmew Were you figure this out?

Can you reproduce the issue by creating a new Git repository (or if applicaple share the one where the issue occurs)?

**Comment by jelmew** [comment]
Hi, yes, it was the tag not being annotated anymore. So this issue is now resolved (only question that remains to me is why annotated tags are needed).

**Comment by janneronkko** [comment]
Thanks for the reply.

About annotated and lightweight tags:

> Git supports two types of tags: lightweight and annotated.
>
> A lightweight tag is very much like a branch that doesn’t change — it’s just a pointer to a specific commit.
>
> Annotated tags, however, are stored as full objects in the Git database. They’re checksummed; contain the tagger name, email, and date; have a tagging message; and can be signed and verified with GNU Privacy Guard (GPG). **It’s generally recommended that you create annotated tags so you can have all this information; but if you want a temporary tag or for some reason don’t want to keep the other information, lightweight tags are available too**.

(emphasis is mine)

https://git-scm.com/book/en/v2/Git-Basics-Tagging

Also from *git tag* man page (https://git-scm.com/docs/git-tag):

> Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight tags by default.

And I made the decision to support only annotated tags in setuptools_autover (this is also one reason why I did implement this libarry; other existing tools also considered lightweight tags and I'm using lightweight tags for other things than releases).

Of course, setuptools_autover could also support parsing version information from lightweight tags also.
